//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Activos_Fijos.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Portal_Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Portal_Entities usando la cadena de conexión encontrada en la sección 'Portal_Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Portal_Entities() : base("name=Portal_Entities", "Portal_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Portal_Entities.
        /// </summary>
        public Portal_Entities(string connectionString) : base(connectionString, "Portal_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Portal_Entities.
        /// </summary>
        public Portal_Entities(EntityConnection connection) : base(connection, "Portal_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<permisos> permisos
        {
            get
            {
                if ((_permisos == null))
                {
                    _permisos = base.CreateObjectSet<permisos>("permisos");
                }
                return _permisos;
            }
        }
        private ObjectSet<permisos> _permisos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet permisos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopermisos(permisos permisos)
        {
            base.AddObject("permisos", permisos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModelo", Name="permisos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class permisos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto permisos.
        /// </summary>
        /// <param name="idpermiso">Valor inicial de la propiedad idpermiso.</param>
        /// <param name="idusuario">Valor inicial de la propiedad idusuario.</param>
        /// <param name="idprograma">Valor inicial de la propiedad idprograma.</param>
        /// <param name="nivel">Valor inicial de la propiedad nivel.</param>
        /// <param name="privilegios">Valor inicial de la propiedad privilegios.</param>
        public static permisos Createpermisos(global::System.Int32 idpermiso, global::System.Int32 idusuario, global::System.Int32 idprograma, global::System.Int32 nivel, global::System.Int32 privilegios)
        {
            permisos permisos = new permisos();
            permisos.idpermiso = idpermiso;
            permisos.idusuario = idusuario;
            permisos.idprograma = idprograma;
            permisos.nivel = nivel;
            permisos.privilegios = privilegios;
            return permisos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idpermiso
        {
            get
            {
                return _idpermiso;
            }
            set
            {
                if (_idpermiso != value)
                {
                    OnidpermisoChanging(value);
                    ReportPropertyChanging("idpermiso");
                    _idpermiso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idpermiso");
                    OnidpermisoChanged();
                }
            }
        }
        private global::System.Int32 _idpermiso;
        partial void OnidpermisoChanging(global::System.Int32 value);
        partial void OnidpermisoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                OnidusuarioChanging(value);
                ReportPropertyChanging("idusuario");
                _idusuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idusuario");
                OnidusuarioChanged();
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idprograma
        {
            get
            {
                return _idprograma;
            }
            set
            {
                OnidprogramaChanging(value);
                ReportPropertyChanging("idprograma");
                _idprograma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idprograma");
                OnidprogramaChanged();
            }
        }
        private global::System.Int32 _idprograma;
        partial void OnidprogramaChanging(global::System.Int32 value);
        partial void OnidprogramaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nivel
        {
            get
            {
                return _nivel;
            }
            set
            {
                OnnivelChanging(value);
                ReportPropertyChanging("nivel");
                _nivel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nivel");
                OnnivelChanged();
            }
        }
        private global::System.Int32 _nivel;
        partial void OnnivelChanging(global::System.Int32 value);
        partial void OnnivelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 privilegios
        {
            get
            {
                return _privilegios;
            }
            set
            {
                OnprivilegiosChanging(value);
                ReportPropertyChanging("privilegios");
                _privilegios = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("privilegios");
                OnprivilegiosChanged();
            }
        }
        private global::System.Int32 _privilegios;
        partial void OnprivilegiosChanging(global::System.Int32 value);
        partial void OnprivilegiosChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModelo", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="idusuario">Valor inicial de la propiedad idusuario.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        /// <param name="correo">Valor inicial de la propiedad correo.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="acceso">Valor inicial de la propiedad acceso.</param>
        /// <param name="status">Valor inicial de la propiedad status.</param>
        /// <param name="id_empresa">Valor inicial de la propiedad id_empresa.</param>
        /// <param name="vendedor">Valor inicial de la propiedad vendedor.</param>
        /// <param name="puesto">Valor inicial de la propiedad puesto.</param>
        /// <param name="fechanacimiento">Valor inicial de la propiedad fechanacimiento.</param>
        /// <param name="perfil">Valor inicial de la propiedad perfil.</param>
        /// <param name="fechaalta">Valor inicial de la propiedad fechaalta.</param>
        /// <param name="clavecorta">Valor inicial de la propiedad clavecorta.</param>
        public static usuarios Createusuarios(global::System.Int32 idusuario, global::System.String nombre, global::System.String usuario, global::System.String clave, global::System.String correo, global::System.DateTime fecha, global::System.Int32 acceso, global::System.Int32 status, global::System.Int32 id_empresa, global::System.Int32 vendedor, global::System.String puesto, global::System.DateTime fechanacimiento, global::System.Int32 perfil, global::System.DateTime fechaalta, global::System.String clavecorta)
        {
            usuarios usuarios = new usuarios();
            usuarios.idusuario = idusuario;
            usuarios.nombre = nombre;
            usuarios.usuario = usuario;
            usuarios.clave = clave;
            usuarios.correo = correo;
            usuarios.fecha = fecha;
            usuarios.acceso = acceso;
            usuarios.status = status;
            usuarios.id_empresa = id_empresa;
            usuarios.vendedor = vendedor;
            usuarios.puesto = puesto;
            usuarios.fechanacimiento = fechanacimiento;
            usuarios.perfil = perfil;
            usuarios.fechaalta = fechaalta;
            usuarios.clavecorta = clavecorta;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String correo
        {
            get
            {
                return _correo;
            }
            set
            {
                OncorreoChanging(value);
                ReportPropertyChanging("correo");
                _correo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("correo");
                OncorreoChanged();
            }
        }
        private global::System.String _correo;
        partial void OncorreoChanging(global::System.String value);
        partial void OncorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 acceso
        {
            get
            {
                return _acceso;
            }
            set
            {
                OnaccesoChanging(value);
                ReportPropertyChanging("acceso");
                _acceso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("acceso");
                OnaccesoChanged();
            }
        }
        private global::System.Int32 _acceso;
        partial void OnaccesoChanging(global::System.Int32 value);
        partial void OnaccesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                Onid_empresaChanging(value);
                ReportPropertyChanging("id_empresa");
                _id_empresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empresa");
                Onid_empresaChanged();
            }
        }
        private global::System.Int32 _id_empresa;
        partial void Onid_empresaChanging(global::System.Int32 value);
        partial void Onid_empresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vendedor
        {
            get
            {
                return _vendedor;
            }
            set
            {
                OnvendedorChanging(value);
                ReportPropertyChanging("vendedor");
                _vendedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vendedor");
                OnvendedorChanged();
            }
        }
        private global::System.Int32 _vendedor;
        partial void OnvendedorChanging(global::System.Int32 value);
        partial void OnvendedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String puesto
        {
            get
            {
                return _puesto;
            }
            set
            {
                OnpuestoChanging(value);
                ReportPropertyChanging("puesto");
                _puesto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("puesto");
                OnpuestoChanged();
            }
        }
        private global::System.String _puesto;
        partial void OnpuestoChanging(global::System.String value);
        partial void OnpuestoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechanacimiento
        {
            get
            {
                return _fechanacimiento;
            }
            set
            {
                OnfechanacimientoChanging(value);
                ReportPropertyChanging("fechanacimiento");
                _fechanacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechanacimiento");
                OnfechanacimientoChanged();
            }
        }
        private global::System.DateTime _fechanacimiento;
        partial void OnfechanacimientoChanging(global::System.DateTime value);
        partial void OnfechanacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 perfil
        {
            get
            {
                return _perfil;
            }
            set
            {
                OnperfilChanging(value);
                ReportPropertyChanging("perfil");
                _perfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("perfil");
                OnperfilChanged();
            }
        }
        private global::System.Int32 _perfil;
        partial void OnperfilChanging(global::System.Int32 value);
        partial void OnperfilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaalta
        {
            get
            {
                return _fechaalta;
            }
            set
            {
                OnfechaaltaChanging(value);
                ReportPropertyChanging("fechaalta");
                _fechaalta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaalta");
                OnfechaaltaChanged();
            }
        }
        private global::System.DateTime _fechaalta;
        partial void OnfechaaltaChanging(global::System.DateTime value);
        partial void OnfechaaltaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clavecorta
        {
            get
            {
                return _clavecorta;
            }
            set
            {
                OnclavecortaChanging(value);
                ReportPropertyChanging("clavecorta");
                _clavecorta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clavecorta");
                OnclavecortaChanged();
            }
        }
        private global::System.String _clavecorta;
        partial void OnclavecortaChanging(global::System.String value);
        partial void OnclavecortaChanged();

        #endregion

    
    }

    #endregion

    
}
