//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Activos_Fijos.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ActivosFijosEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ActivosFijosEntities usando la cadena de conexión encontrada en la sección 'ActivosFijosEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ActivosFijosEntities() : base("name=ActivosFijosEntities", "ActivosFijosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ActivosFijosEntities.
        /// </summary>
        public ActivosFijosEntities(string connectionString) : base(connectionString, "ActivosFijosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ActivosFijosEntities.
        /// </summary>
        public ActivosFijosEntities(EntityConnection connection) : base(connection, "ActivosFijosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<bitacora_activos> bitacora_activos
        {
            get
            {
                if ((_bitacora_activos == null))
                {
                    _bitacora_activos = base.CreateObjectSet<bitacora_activos>("bitacora_activos");
                }
                return _bitacora_activos;
            }
        }
        private ObjectSet<bitacora_activos> _bitacora_activos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<catalogo_estatus> catalogo_estatus
        {
            get
            {
                if ((_catalogo_estatus == null))
                {
                    _catalogo_estatus = base.CreateObjectSet<catalogo_estatus>("catalogo_estatus");
                }
                return _catalogo_estatus;
            }
        }
        private ObjectSet<catalogo_estatus> _catalogo_estatus;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<clasificaciones> clasificaciones
        {
            get
            {
                if ((_clasificaciones == null))
                {
                    _clasificaciones = base.CreateObjectSet<clasificaciones>("clasificaciones");
                }
                return _clasificaciones;
            }
        }
        private ObjectSet<clasificaciones> _clasificaciones;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<grupos> grupos
        {
            get
            {
                if ((_grupos == null))
                {
                    _grupos = base.CreateObjectSet<grupos>("grupos");
                }
                return _grupos;
            }
        }
        private ObjectSet<grupos> _grupos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<grupos_detalles> grupos_detalles
        {
            get
            {
                if ((_grupos_detalles == null))
                {
                    _grupos_detalles = base.CreateObjectSet<grupos_detalles>("grupos_detalles");
                }
                return _grupos_detalles;
            }
        }
        private ObjectSet<grupos_detalles> _grupos_detalles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ubicaciones> ubicaciones
        {
            get
            {
                if ((_ubicaciones == null))
                {
                    _ubicaciones = base.CreateObjectSet<ubicaciones>("ubicaciones");
                }
                return _ubicaciones;
            }
        }
        private ObjectSet<ubicaciones> _ubicaciones;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<activos> activos
        {
            get
            {
                if ((_activos == null))
                {
                    _activos = base.CreateObjectSet<activos>("activos");
                }
                return _activos;
            }
        }
        private ObjectSet<activos> _activos;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet bitacora_activos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTobitacora_activos(bitacora_activos bitacora_activos)
        {
            base.AddObject("bitacora_activos", bitacora_activos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet catalogo_estatus. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocatalogo_estatus(catalogo_estatus catalogo_estatus)
        {
            base.AddObject("catalogo_estatus", catalogo_estatus);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet clasificaciones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToclasificaciones(clasificaciones clasificaciones)
        {
            base.AddObject("clasificaciones", clasificaciones);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet grupos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTogrupos(grupos grupos)
        {
            base.AddObject("grupos", grupos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet grupos_detalles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTogrupos_detalles(grupos_detalles grupos_detalles)
        {
            base.AddObject("grupos_detalles", grupos_detalles);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ubicaciones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToubicaciones(ubicaciones ubicaciones)
        {
            base.AddObject("ubicaciones", ubicaciones);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet activos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToactivos(activos activos)
        {
            base.AddObject("activos", activos);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivosFijosModel", Name="activos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class activos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto activos.
        /// </summary>
        /// <param name="id_activo">Valor inicial de la propiedad id_activo.</param>
        /// <param name="nombre_corto">Valor inicial de la propiedad nombre_corto.</param>
        /// <param name="descripcion_detallada">Valor inicial de la propiedad descripcion_detallada.</param>
        /// <param name="fecha_adquisicion">Valor inicial de la propiedad fecha_adquisicion.</param>
        /// <param name="costo">Valor inicial de la propiedad costo.</param>
        /// <param name="id_clasificacion">Valor inicial de la propiedad id_clasificacion.</param>
        /// <param name="codigo_barras">Valor inicial de la propiedad codigo_barras.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static activos Createactivos(global::System.Int64 id_activo, global::System.String nombre_corto, global::System.String descripcion_detallada, global::System.DateTime fecha_adquisicion, global::System.Decimal costo, global::System.Int64 id_clasificacion, global::System.String codigo_barras, global::System.String estatus)
        {
            activos activos = new activos();
            activos.id_activo = id_activo;
            activos.nombre_corto = nombre_corto;
            activos.descripcion_detallada = descripcion_detallada;
            activos.fecha_adquisicion = fecha_adquisicion;
            activos.costo = costo;
            activos.id_clasificacion = id_clasificacion;
            activos.codigo_barras = codigo_barras;
            activos.estatus = estatus;
            return activos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_activo
        {
            get
            {
                return _id_activo;
            }
            set
            {
                if (_id_activo != value)
                {
                    Onid_activoChanging(value);
                    ReportPropertyChanging("id_activo");
                    _id_activo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_activo");
                    Onid_activoChanged();
                }
            }
        }
        private global::System.Int64 _id_activo;
        partial void Onid_activoChanging(global::System.Int64 value);
        partial void Onid_activoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_corto
        {
            get
            {
                return _nombre_corto;
            }
            set
            {
                Onnombre_cortoChanging(value);
                ReportPropertyChanging("nombre_corto");
                _nombre_corto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_corto");
                Onnombre_cortoChanged();
            }
        }
        private global::System.String _nombre_corto;
        partial void Onnombre_cortoChanging(global::System.String value);
        partial void Onnombre_cortoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion_detallada
        {
            get
            {
                return _descripcion_detallada;
            }
            set
            {
                Ondescripcion_detalladaChanging(value);
                ReportPropertyChanging("descripcion_detallada");
                _descripcion_detallada = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion_detallada");
                Ondescripcion_detalladaChanged();
            }
        }
        private global::System.String _descripcion_detallada;
        partial void Ondescripcion_detalladaChanging(global::System.String value);
        partial void Ondescripcion_detalladaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_adquisicion
        {
            get
            {
                return _fecha_adquisicion;
            }
            set
            {
                Onfecha_adquisicionChanging(value);
                ReportPropertyChanging("fecha_adquisicion");
                _fecha_adquisicion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_adquisicion");
                Onfecha_adquisicionChanged();
            }
        }
        private global::System.DateTime _fecha_adquisicion;
        partial void Onfecha_adquisicionChanging(global::System.DateTime value);
        partial void Onfecha_adquisicionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal costo
        {
            get
            {
                return _costo;
            }
            set
            {
                OncostoChanging(value);
                ReportPropertyChanging("costo");
                _costo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("costo");
                OncostoChanged();
            }
        }
        private global::System.Decimal _costo;
        partial void OncostoChanging(global::System.Decimal value);
        partial void OncostoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_clasificacion
        {
            get
            {
                return _id_clasificacion;
            }
            set
            {
                Onid_clasificacionChanging(value);
                ReportPropertyChanging("id_clasificacion");
                _id_clasificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_clasificacion");
                Onid_clasificacionChanged();
            }
        }
        private global::System.Int64 _id_clasificacion;
        partial void Onid_clasificacionChanging(global::System.Int64 value);
        partial void Onid_clasificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo_barras
        {
            get
            {
                return _codigo_barras;
            }
            set
            {
                Oncodigo_barrasChanging(value);
                ReportPropertyChanging("codigo_barras");
                _codigo_barras = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo_barras");
                Oncodigo_barrasChanged();
            }
        }
        private global::System.String _codigo_barras;
        partial void Oncodigo_barrasChanging(global::System.String value);
        partial void Oncodigo_barrasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_asignacion
        {
            get
            {
                return _fecha_asignacion;
            }
            set
            {
                Onfecha_asignacionChanging(value);
                ReportPropertyChanging("fecha_asignacion");
                _fecha_asignacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_asignacion");
                Onfecha_asignacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_asignacion;
        partial void Onfecha_asignacionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_asignacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_empleado
        {
            get
            {
                return _id_empleado;
            }
            set
            {
                Onid_empleadoChanging(value);
                ReportPropertyChanging("id_empleado");
                _id_empleado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empleado");
                Onid_empleadoChanged();
            }
        }
        private Nullable<global::System.Int32> _id_empleado;
        partial void Onid_empleadoChanging(Nullable<global::System.Int32> value);
        partial void Onid_empleadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_ubicacion
        {
            get
            {
                return _id_ubicacion;
            }
            set
            {
                Onid_ubicacionChanging(value);
                ReportPropertyChanging("id_ubicacion");
                _id_ubicacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_ubicacion");
                Onid_ubicacionChanged();
            }
        }
        private Nullable<global::System.Int32> _id_ubicacion;
        partial void Onid_ubicacionChanging(Nullable<global::System.Int32> value);
        partial void Onid_ubicacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] imagen
        {
            get
            {
                return StructuralObject.GetValidValue(_imagen);
            }
            set
            {
                OnimagenChanging(value);
                ReportPropertyChanging("imagen");
                _imagen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imagen");
                OnimagenChanged();
            }
        }
        private global::System.Byte[] _imagen;
        partial void OnimagenChanging(global::System.Byte[] value);
        partial void OnimagenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> idcompra
        {
            get
            {
                return _idcompra;
            }
            set
            {
                OnidcompraChanging(value);
                ReportPropertyChanging("idcompra");
                _idcompra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idcompra");
                OnidcompraChanged();
            }
        }
        private Nullable<global::System.Int64> _idcompra;
        partial void OnidcompraChanging(Nullable<global::System.Int64> value);
        partial void OnidcompraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivosFijosModel", Name="bitacora_activos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bitacora_activos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto bitacora_activos.
        /// </summary>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="hora">Valor inicial de la propiedad hora.</param>
        /// <param name="id_activo">Valor inicial de la propiedad id_activo.</param>
        /// <param name="id_usuario_creador">Valor inicial de la propiedad id_usuario_creador.</param>
        /// <param name="accion">Valor inicial de la propiedad accion.</param>
        public static bitacora_activos Createbitacora_activos(global::System.DateTime fecha, global::System.TimeSpan hora, global::System.Int64 id_activo, global::System.Int64 id_usuario_creador, global::System.String accion)
        {
            bitacora_activos bitacora_activos = new bitacora_activos();
            bitacora_activos.fecha = fecha;
            bitacora_activos.hora = hora;
            bitacora_activos.id_activo = id_activo;
            bitacora_activos.id_usuario_creador = id_usuario_creador;
            bitacora_activos.accion = accion;
            return bitacora_activos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan hora
        {
            get
            {
                return _hora;
            }
            set
            {
                if (_hora != value)
                {
                    OnhoraChanging(value);
                    ReportPropertyChanging("hora");
                    _hora = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hora");
                    OnhoraChanged();
                }
            }
        }
        private global::System.TimeSpan _hora;
        partial void OnhoraChanging(global::System.TimeSpan value);
        partial void OnhoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_activo
        {
            get
            {
                return _id_activo;
            }
            set
            {
                if (_id_activo != value)
                {
                    Onid_activoChanging(value);
                    ReportPropertyChanging("id_activo");
                    _id_activo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_activo");
                    Onid_activoChanged();
                }
            }
        }
        private global::System.Int64 _id_activo;
        partial void Onid_activoChanging(global::System.Int64 value);
        partial void Onid_activoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario_creador
        {
            get
            {
                return _id_usuario_creador;
            }
            set
            {
                Onid_usuario_creadorChanging(value);
                ReportPropertyChanging("id_usuario_creador");
                _id_usuario_creador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_creador");
                Onid_usuario_creadorChanged();
            }
        }
        private global::System.Int64 _id_usuario_creador;
        partial void Onid_usuario_creadorChanging(global::System.Int64 value);
        partial void Onid_usuario_creadorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String accion
        {
            get
            {
                return _accion;
            }
            set
            {
                OnaccionChanging(value);
                ReportPropertyChanging("accion");
                _accion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("accion");
                OnaccionChanged();
            }
        }
        private global::System.String _accion;
        partial void OnaccionChanging(global::System.String value);
        partial void OnaccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String observaciones
        {
            get
            {
                return _observaciones;
            }
            set
            {
                OnobservacionesChanging(value);
                ReportPropertyChanging("observaciones");
                _observaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("observaciones");
                OnobservacionesChanged();
            }
        }
        private global::System.String _observaciones;
        partial void OnobservacionesChanging(global::System.String value);
        partial void OnobservacionesChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivosFijosModel", Name="catalogo_estatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class catalogo_estatus : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto catalogo_estatus.
        /// </summary>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        public static catalogo_estatus Createcatalogo_estatus(global::System.String estatus, global::System.String nombre, global::System.String descripcion)
        {
            catalogo_estatus catalogo_estatus = new catalogo_estatus();
            catalogo_estatus.estatus = estatus;
            catalogo_estatus.nombre = nombre;
            catalogo_estatus.descripcion = descripcion;
            return catalogo_estatus;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                if (_estatus != value)
                {
                    OnestatusChanging(value);
                    ReportPropertyChanging("estatus");
                    _estatus = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("estatus");
                    OnestatusChanged();
                }
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivosFijosModel", Name="clasificaciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clasificaciones : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto clasificaciones.
        /// </summary>
        /// <param name="id_clasificacion">Valor inicial de la propiedad id_clasificacion.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static clasificaciones Createclasificaciones(global::System.Int64 id_clasificacion, global::System.String nombre, global::System.String estatus)
        {
            clasificaciones clasificaciones = new clasificaciones();
            clasificaciones.id_clasificacion = id_clasificacion;
            clasificaciones.nombre = nombre;
            clasificaciones.estatus = estatus;
            return clasificaciones;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_clasificacion
        {
            get
            {
                return _id_clasificacion;
            }
            set
            {
                if (_id_clasificacion != value)
                {
                    Onid_clasificacionChanging(value);
                    ReportPropertyChanging("id_clasificacion");
                    _id_clasificacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_clasificacion");
                    Onid_clasificacionChanged();
                }
            }
        }
        private global::System.Int64 _id_clasificacion;
        partial void Onid_clasificacionChanging(global::System.Int64 value);
        partial void Onid_clasificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivosFijosModel", Name="grupos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class grupos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto grupos.
        /// </summary>
        /// <param name="id_grupo">Valor inicial de la propiedad id_grupo.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static grupos Creategrupos(global::System.Int32 id_grupo, global::System.String nombre, global::System.String estatus)
        {
            grupos grupos = new grupos();
            grupos.id_grupo = id_grupo;
            grupos.nombre = nombre;
            grupos.estatus = estatus;
            return grupos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_grupo
        {
            get
            {
                return _id_grupo;
            }
            set
            {
                if (_id_grupo != value)
                {
                    Onid_grupoChanging(value);
                    ReportPropertyChanging("id_grupo");
                    _id_grupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_grupo");
                    Onid_grupoChanged();
                }
            }
        }
        private global::System.Int32 _id_grupo;
        partial void Onid_grupoChanging(global::System.Int32 value);
        partial void Onid_grupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivosFijosModel", Name="grupos_detalles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class grupos_detalles : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto grupos_detalles.
        /// </summary>
        /// <param name="id_grupo">Valor inicial de la propiedad id_grupo.</param>
        /// <param name="id_activo">Valor inicial de la propiedad id_activo.</param>
        public static grupos_detalles Creategrupos_detalles(global::System.Int32 id_grupo, global::System.Int32 id_activo)
        {
            grupos_detalles grupos_detalles = new grupos_detalles();
            grupos_detalles.id_grupo = id_grupo;
            grupos_detalles.id_activo = id_activo;
            return grupos_detalles;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_grupo
        {
            get
            {
                return _id_grupo;
            }
            set
            {
                if (_id_grupo != value)
                {
                    Onid_grupoChanging(value);
                    ReportPropertyChanging("id_grupo");
                    _id_grupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_grupo");
                    Onid_grupoChanged();
                }
            }
        }
        private global::System.Int32 _id_grupo;
        partial void Onid_grupoChanging(global::System.Int32 value);
        partial void Onid_grupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_activo
        {
            get
            {
                return _id_activo;
            }
            set
            {
                if (_id_activo != value)
                {
                    Onid_activoChanging(value);
                    ReportPropertyChanging("id_activo");
                    _id_activo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_activo");
                    Onid_activoChanged();
                }
            }
        }
        private global::System.Int32 _id_activo;
        partial void Onid_activoChanging(global::System.Int32 value);
        partial void Onid_activoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivosFijosModel", Name="ubicaciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ubicaciones : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ubicaciones.
        /// </summary>
        /// <param name="id_ubicacion">Valor inicial de la propiedad id_ubicacion.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="domicilio">Valor inicial de la propiedad domicilio.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static ubicaciones Createubicaciones(global::System.Int64 id_ubicacion, global::System.String nombre, global::System.String domicilio, global::System.String estatus)
        {
            ubicaciones ubicaciones = new ubicaciones();
            ubicaciones.id_ubicacion = id_ubicacion;
            ubicaciones.nombre = nombre;
            ubicaciones.domicilio = domicilio;
            ubicaciones.estatus = estatus;
            return ubicaciones;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_ubicacion
        {
            get
            {
                return _id_ubicacion;
            }
            set
            {
                if (_id_ubicacion != value)
                {
                    Onid_ubicacionChanging(value);
                    ReportPropertyChanging("id_ubicacion");
                    _id_ubicacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_ubicacion");
                    Onid_ubicacionChanged();
                }
            }
        }
        private global::System.Int64 _id_ubicacion;
        partial void Onid_ubicacionChanging(global::System.Int64 value);
        partial void Onid_ubicacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String domicilio
        {
            get
            {
                return _domicilio;
            }
            set
            {
                OndomicilioChanging(value);
                ReportPropertyChanging("domicilio");
                _domicilio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("domicilio");
                OndomicilioChanged();
            }
        }
        private global::System.String _domicilio;
        partial void OndomicilioChanging(global::System.String value);
        partial void OndomicilioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();

        #endregion

    
    }

    #endregion

    
}
